# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FiRe-Service & Consulting
email: info@fire-service.de
description: FiRe-Service & Consulting
description_en: FiRe-Service & Consulting
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
version: 3.1.6
markdown: kramdown
